### ISSUE TITLE
Request URLs for https request are missing domains in HAR when using littleproxy version of browsermob-rest

### ISSUE THREAD

**Issue by gempesaw** [lightbody/browsermob-proxy#227]
Hey, I recently noticed that the request urls in the HAR that I get back from the `--use-littleproxy true` REST api don't have the entire URL for https requests ? The url is truncated to just the path - for a request to `https://www.google.com/`, I'm just seeing `/` in the HAR's request url entry.

truncated part of har for a request to https://www.google.com:

```
"request": {
                    "bodySize": 0,
                    "comment": "",
                    "cookies": [],
                    "headers": [],
                    "headersSize": 80,
                    "httpVersion": "HTTP/1.1",
                    "method": "GET",
                    "queryString": [],
                    "url": "/"
                },
```

and I'd be expecting `"url": "https://www.google.com"` instead of `"/"`. 

just pulled frmo master, did an `mvn -Prelease -DskipTests clean install` and started up bmp via `bin/browsermob-proxy --use-littleproxy true`, and then ran the following curls:

```bash
# make a proxy
curl -X POST 0.0.0.0:8080/proxy
# start a har
curl -X PUT 0.0.0.0:8080/proxy/8081/har
# request google over our proxy
curl -k -x 0.0.0.0:8081 https://www.google.com -o /dev/null
# get the har back
curl 0.0.0.0:8080/proxy/8081/har
```

and, yeah, there's no issue for http urls, they're shown in their entirety in the url entry. maybe related to #178 ? cheers :)

**Comment by ryanlevell** [comment]
I had a similar experience today when using WebDriver with the ResponseFilter. I did not look into it, though, and am not sure if it was https only. I will have to take a closer look.

**Comment by jekh** [comment]
Thank you for finding this, @gempesaw. I'm actually surprised that HTTP URLs are showing up correctly, at least after the first request. Were you verifying the first request only, or the second (and subsequent) requests to the same host as well? With HTTPS, the full URL will be present in the CONNECT, but after that only the path to the resource will be present in the URI, which explains why it is never captured in the HAR.

Getting the full URL as the HAR spec demands is actually a bit trickier than you would expect because the scheme is not actually part of the message. I'll have to poke around a bit to determine what's possible.

This defect and the POST parameter defect @ryanlevell found yesterday really underscore the need for more robust unit tests of the HAR functionality. The legacy tests + the few new HAR tests just don't provide adequate coverage. Beefing up the HAR unit tests should be a top priority after the beta-1 release is finalized.

Thanks for your help testing this!

**Comment by gempesaw** [comment]
Ah, that makes sense about the  CONNECT & subsequent requests. The HTTP url was the first one, as you correctly surmised. I'll double check it if further requests to the same host over http have the issue. 

I was able to find a workaround for my particular issue, so it's not blocking me at the moment. I'll see if I can compose a failing test at some point.

**Comment by jekh** [comment]
This should (hopefully) be fixed in master now. Let me know if you still see this issue.

**Comment by gempesaw** [comment]
Awesome, verified fixed in master as expected! Thanks!
