### ISSUE TITLE
browsermob-core-littleproxy does not support remote connections

### ISSUE THREAD

**Issue by nthexwn** [lightbody/browsermob-proxy#230]
In order to support remote connections (IE: connecting to the proxy server from another physical server) LittleProxy required the following method to be called before starting (usually as part of a builder chain):

HttpProxyServerBootstrap.withAllowLocalOnly(false);

I still need this so that my Selenium tests can be run through RemoteWebDrivers via Selenium Grid.  All of these RemoteWebDrivers are configured to connect back to the proxy server which is running on the original test machine.  If this flag is not set then those connections are blocked and the tests all fail on an "unable to connect to proxy" page.

I understand that opening up the proxy to the rest of the world by default might not be desirable, so I was wondering if it would be possible to adjust the BrowserMob API to make this configurable?  Perhaps it's already there and I'm just not seeing it?

Thanks,
-Alex

**Comment by jekh** [comment]
BrowserMob Proxy should not need to call withAllowLocalOnly() because BMP always sets a client bind address via the LP bootstrap method withAddress(). By default, BMP will bind to the wildcard address, which will listen on all local network interfaces. You can override this by calling `BrowserMobProxy.start(port, clientBindAddress)`. There is also a deprecated `LegacyProxyServer.setLocalHost(clientBindAddress)` method that will set the bind address.

With the default behavior, you should see something like this when you start BMP:
```
org.littleshoot.proxy.impl.DefaultHttpProxyServer - Starting proxy at address: 0.0.0.0/0.0.0.0:0
org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy listening with TCP transport
org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy started at address: /0:0:0:0:0:0:0:0:60570
```

The `Proxy started at address: /0:0:0:0:0:0:0:0:60570` means that BMP will listen for connections on port 60570 of all network interfaces.

If you're having trouble connecting to the proxy, it may be some other network-related issue. Can you provide any further information?

**Comment by nthexwn** [comment]
My apologies, this was a configuration problem on our end.  It's working fine now without any changes to the proxy.  Closing.
