### ISSUE TITLE
Implement certificate spoofing with MITM for the LittleProxy implementation

### ISSUE THREAD

**Issue by jekh** [lightbody/browsermob-proxy#246]
The legacy implementation supports certificate spoofing, but this support was removed in the LittleProxy implementation because LittleProxy does not support it out-of-the-box.

**Comment by gempesaw** [comment]
Hi @jekh! Do you happen to have an update on the status of on-the-fly certificate spoofing for MITM with LittleProxy mode of BMP? 

I'm trying to MITM SSL traffic from Safari on an iOS device, and my lack of familiarity with SSL & certs is holding me back. For manual testing we've been able to successfully MITM our iOS device traffic with CharlesProxy, but I don't know how to get the same thing working with BMP. I've downloaded the `cybervillains.cer` to the iOS device and trusted it there (similar to how CharlesProxy requires us to install a profile to the iOS device). But, it doesn't impact the Safari traffic - I still have to manually accept the cert for each new domain that Safari makes a request to. 

As always, thanks so much for all the excellent work on BMP! I had no idea that you were also a contributor for LittleProxy as well, which we also now use heavily since we rely on BMP's littleproxy mode every single day. Thaaanks and happy holidays!

**Comment by jekh** [comment]
Hi @gempesaw, I do in fact have an update. The MITM work is nearly complete. I'm currently finishing up testing and documentation. I expect to have beta-4 released this weekend, including the new MITM engine.

The HTTP clients (i.e. Chrome/Safari/Firefox, or Apache HTTP Client, or whichever client you use) will still need to trust a "fake" CA root certificate, such as the Cybervillains certificate currently included in BMP. But as long as the client trusts that root certificate, it will automatically trust the SSL connections BMP/LP opens to upstream hosts.

**Comment by gempesaw** [comment]
What! Wow, that is excellent news! Very glad to hear it :)

> will still need to trust a "fake" CA root certificate, such as the Cybervillains certificate currently included in BMP. 

cool! this file is the one in an `ssl-support` folder with the `.cer` extension right?

**Comment by jekh** [comment]
Beta-4 is out with the new MITM support. The certificate file has changed to `ca-certificate-rsa.cer`, but otherwise everything you said is correct.

If this works for you now, we can finally close this issue!

**Comment by gempesaw** [comment]
Ahhhh this is excellent stuff, @jekh. I've tried this out on an iTouch and it works like a charm with beta-4. Thanks much!

**Comment by jekh** [comment]
That's great news! I'll go ahead and close this issue, then.
