### ISSUE TITLE
How to create a embedded proxy similar to browsermob-proxy

### ISSUE THREAD

**Issue by karunakaranvrv** [lightbody/browsermob-proxy#256]
@jekh 

We are starting browser-mob by following:-

package example.tests;

import net.lightbody.bmp.BrowserMobProxyServer;

public class Sample {

	public static void main(String args[]){
		ProxyServer server = new ProxyServer(4444);
		server.start();
		server.seleniumProxy();
	}

}

server.seleniumProxy(); - Here we are creating seleniumProxy(). Is it possible to create normal proxy similar to following:-

1. ./browsermob-proxy --port 9090
2. curl -X POST http://localhost:9090/proxy

**Comment by jekh** [comment]
I don't completely understand your question. However, it looks like you're starting the proxy correctly. I would recommend using the `browsermob-core-littleproxy` module instead of the legacy module (see the examples in the README.md file). Still, what you're doing is correct and should work. Both the Java code and the command-line/standalone mode code you pasted looks right.

Are you encountering a specific error or problem? Perhaps you could restate your question another way?

**Comment by samuelalexanderg** [comment]
We tried using browsermob-core-littleproxy as well. But the result is same.

Our issue is, when we create the proxy using the below steps, all our http requests in our tests are passed via proxy and we are able to get the har.

    ./browsermob-proxy --port 9090
    curl -X POST http://localhost:9090/proxy

But when we do the same using JAVA (embedded)
public static void main(String args[]){
    ProxyServer server = new ProxyServer(4444);
    server.start();
    server.seleniumProxy();
}
the http requests are not passed via proxy. har is empty.

Please note that in both the cases we are not setting the proxy as capabilities. 
We use sauce connect from sacue lab which will send the request via proxy if we configure it accordingly.

Refer http://sauceio.com/index.php/2013/09/sauce-labs-and-yes-the-browsermob-proxy/

Are we missing anything here?

**Comment by mediga** [comment]
what i understand is you are trying to start browsermob proxy from a java program instead of command line.

you just need to do this  with your main method.

BrowserMobProxy proxy = new BrowserMobProxyServer();
    proxy.start(0); //or you can assign your desired port if you like  proxy.start(8888);
    // get the JVM-assigned port and get to work!
    int port = proxy.getPort();

you really dont need server.seleniumProxy();

Once the proxy is started, you can use REST commands issued from a java program or from a curl to get the har logs.

**Comment by jekh** [comment]
> Please note that in both the cases we are not setting the proxy as capabilities. 

@samuelalexanderg - If you're not using the selenium `Proxy` object that `server.seleniumProxy()` returns, then calling seleniumProxy() will not do anything useful. The purpose of that method is to return a `Proxy` object that you can use when configuring selenium. If you're not using selenium, you need to configure your browser or HTTP client to use BMP using the configuration mechanism provided by your browser/HTTP client/testing framework. See the README file for more information.

You seem to be using the embedded mode version of BMP, which is fine; but when you use the embedded mode, you need tell BMP to capture HAR content, retrieve the HAR, etc. in your code. You can't use REST calls to control BMP if you start BMP from java code. There are examples of capturing HAR data in embedded mode in the README.

I'm not familiar with Sauce Labs so I can't speak to how to configure their systems to use a proxy. But what @mediga said is correct and sounds like a good starting point for you.

Hope that helps!

**Comment by jekh** [comment]
I'm going to close this issue since the question has been answered.
