### ISSUE TITLE
Cannot open a specific URL, browsermob fails.

### ISSUE THREAD

**Issue by fcruxen** [lightbody/browsermob-proxy#260]
Hi there,

We've been using browsermob daily to gather webmetrics for our clients. This week one particular URL is failing in browsermob. Using selenium without browsermob opens the URL, when using browsermob the proxy reply with a domain not found error. It seems  that the ssl handshake is made, it starts downloading the assets, but fails.

To emulate this error is quite simple, put browsermob proxy on, point the browser to the proxy, and try opening the following url: https://secure.homecenter.com.co/homecenter-co/checkout/purchaseFlow.jsp?_requestid=9938

If any log/debug is needed, please let me know. You can check this error in any OS, with any browser.

**Comment by fcruxen** [comment]
using 2.0-beta9, built using maven 3.2.5, I don't have this error anymore.

**Comment by jekh** [comment]
What version were you using originally? beta-9 is very old.

**Comment by fcruxen** [comment]
in 2.0.0 stable, 2.1-beta and master in github I have the same error.

**Comment by fcruxen** [comment]
sorry, my post about the working version in incomplete. the most important change is that I used jre 1.6 to compile/run the working version, the stable/2.1 versions require libs that do not exist in jre 1.6 (eg: java.nio.charset.StandardCharsets), so I could not build them with maven to check if running on 1.6 they would work as well. again, sorry about my stupidity, I am not a good/experienced java dev.

**Comment by jekh** [comment]
@fcruxen -- no worries! This is not a stupid question at all.

Is it a requirement that you _run_ BMP on a Java 1.6 JVM? The reason I ask is that we have officially eliminated support for Java 1.6 in BMP. (1.6 has been end-of-lifed for [over 2 years](http://www.oracle.com/technetwork/java/eol-135779.html#Java6-end-public-updates), and even 1.7 is now EOL.) If you are running on a 1.7 or later JVM, you should be able to run 2.0.0 or 2.1.0-beta-1+.

If you absolutely have to run on Java 6, there is a Java 6 compatible version of 2.0.0 in PR #149. I just updated the PR with instructions on checking it out and building it. It contains all of the 2.0.0 fixes, which have been quite significant since beta-9 came out. I highly recommend it over the beta-9 release.

Note though that 2.0.0 is the last version of BMP that the Java 6 PR will be maintained for. There will be no Java 6-compatible release of 2.1.0+.

**Comment by fcruxen** [comment]
No I am just running on java 6 because I do believe this problem occurs only when using jre 1.7+.

As I said, I wasn't able to compile/run 2.0.0 stable or 2.1 using the jre 1.6 to check if only changing the jre those versions would work as well. 

I am just using it because right now this combo jre 1.6 + beta-9 is the only combination that works.

**Comment by fcruxen** [comment]
another update, got some time this weekend to look better at it. using 1.8 or 1.7, this is the error browsermob is throwing: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: Certificates does not conform to algorithm constraints when requesting https://secure.homecenter.com.co/homecenter-co/checkout/purchaseFlow.jsp?_requestid=9938

I've googled about it and all the resources points to commenting one flag in security file:
jdk.certpath.disabledAlgorithms

I did so, but still no go, same error. does browsermob uses it's own configuration, overriding the global one? Thanks in advance.

**Comment by jekh** [comment]
@fcruxen - I know it's been a while, but I finally have an update on this issue. You were seeing the CertificateException because the website (secure.homecenter.com.co) was using an certificate that used MD2 and/or an RSA key with less than 1024 bits, both of which are disallowed by default after Java 7u40. The solution you described, using the jdk.certpath.disabledAlgorithms parameter, should have fixed the issue; if not, it may have been a JDK configuration issue.

The website appears to have updated its certificates since this issue was created and now works properly, so I'm going to close this issue.
