### ISSUE TITLE
Browsermob Proxy not clean up connection after webdriver quits

### ISSUE THREAD

**Issue by chemicwepn** [lightbody/browsermob-proxy#290]
I am using 2.0 beta 2. I notic a new thread named "LittleProxy-ClientToProxyAcceptor-0" whenever I do a get(url) with the phantomjs webdriver, that thread doesn't get closed after I did a quit(), it remains running. Next I did a get(url) again, a thread with same name is created and running and never gets close. I want to run the getHar() every couple minutes without starting the proxy server every time for performance reason. I would image it's expensive to create the proxy server for every getHar(). Correct me if I am wrong. With current implementation, I basically I have a thread leak if I don't call the stop method of the proxy.  
![image](https://cloud.githubusercontent.com/assets/2215603/8949756/297752ca-3553-11e5-88a9-2d0c54274c99.png)

//called only once during initialization
public void setupProxy() {
BrowserMobProxy proxy = new BrowserMobProxyServer();      
    proxy.setConnectTimeout(20, TimeUnit.SECONDS);
    proxy.setIdleConnectionTimeout(10, TimeUnit.SECONDS);
    proxy.setRequestTimeout(20, TimeUnit.SECONDS);
proxy.start(0);
Proxy prox = ClientUtil.createSeleniumProxy(proxy);
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(CapabilityType.PROXY, prox);
capabilities.setCapability(PhantomJSDriverService.PHANTOMJS_CLI_ARGS, PHANTOMJSCLIARGS);
    capabilities.setCapability(PhantomJSDriverService.PHANTOMJS_GHOSTDRIVER_CLI_ARGS, new String[] {"--logLevel=INFO"});
    capabilities.setJavascriptEnabled(true);
    capabilities.setCapability("takesScreenshot", false);
}

//This method is called every couple minutes. 
public Har getHar(String target) {
try{
    PhantomJSDriver  driver = new PhantomJSDriver(capabilities);
driver.manage().timeouts().setScriptTimeout(5, TimeUnit.SECONDS);
      driver.manage().timeouts().pageLoadTimeout(20, TimeUnit.SECONDS);
proxy.newHar(target);

 driver.get(target);
 Har har = proxy.getHar();
Thread.sleep(20_000);
 driver.quit();
return har;
}
    catch(Exception e) {
      e.printStackTrace();  
      this.error = e.getMessage();
    }
return null;
}

Is this the right way to do it? The only reason I don't want to call proxy.stop() is because of performance consideration.

**Comment by jekh** [comment]
It looks like you are using the proxy correctly. You're right that stopping and starting the proxy for every request is probably too much, but if you're running a series of tests, it's pretty common to start and stop the proxy for every test (for example, calling .start() and .stop() in JUnit @Before and @After methods). If you just want to clear the har between requests, you can use proxy.newHar().

>I basically I have a thread leak if I don't call the stop method of the proxy.

Netty uses thread pools, so it's normal to have some idle threads in the pool even after a request completes. Currently LittleProxy allows up to 16 worker threads and 2 acceptor threads, and threads are not immediately reclaimed after a request finishes (this is by design).

Looking at your VisualVM screenshot, it is odd that you have so many "ClientToProxyAcceptor-0" threads. Are you sure you're only calling setupProxy() once? If you're calling proxy.start() multiple times without calling .stop() or .abort(), you will end up with an ever-growing number of threads and proxy instances.

**Comment by chemicwepn** [comment]
Ha! Yes, you are right. I looked at my code again, the setupProxy() was called multiple times. My bad. That solves my problem! Thanks you very much for your help. The issue is invalid. I will close it now.
