### ISSUE TITLE
407 Proxy Authentication

### ISSUE THREAD

**Issue by natesreich** [lightbody/browsermob-proxy#358]
Hello,

I am trying to use Browsermob Proxy with an Upstream Proxy.

Here's what I have tried:

--
//============================
// ATTEMPT #1: Set Regular Header
//============================

- POST (http://{$this->browsermob_url}/proxy?httpProxy={$this->httpProxy})
- POST ("http://{$this->browsermob_url}/proxy/{$this->port}/headers",
  array('Content-Type' => 'application/json'),
  array("Proxy-Authorization"=>"Basic {base64_encoded_username/password}","User-Agent"=>"iPhone"))

Results:
- "User-Agent"=>"iPhone" is for testing purposes, and it's set when I retrieve http://whatsmyuseragent.com/ without the httpProxy
- However, when httpProxy is enabled, I keep getting 407 Authentication Error

--

At this point I realized that the httpProxy was requiring authentication prior the page being requested. Basically, it sends a header with "Proxy-Authenticate: Basic realm="{whatever}"

I figured I would try to intercept this header.

--

//============================
// ATTEMPT #2: Intercept Headers
//============================

- POST (http://{$this->browsermob_url}/proxy?httpProxy={$this->httpProxy})
- POST ("http://{$this->browsermob_url}/proxy/{$this->port}/filter/response",
  array('Content-Type'=>'text/plain'),
  "response.headers().remove('Proxy-Authenticate');request.headers().add('Proxy-Authorization', 'Basic {base64_encoded_username/password}')"

Results:
- Same as Attempt #1 above

--

Could someone please guide me on how I can intercept Proxy-Authenticate headers, and respond with the correct Proxy-Authorization headers?

Thank you!

**Comment by jekh** [comment]
The problem here is twofold. First, LittleProxy to my knowledge does not support resending a request, so you cannot react to a Proxy-Authenticate header in a response filter and resend the request to the server with a Proxy-Authorization header. It's simply not possible with the current architecture. I'm going to look into that a bit more and may open a LP issue; I can see that functionality being very useful in other scenarios as well.

The second problem is that the Proxy-Authorization header is a hop-by-hop header, so LittleProxy is stripping it out before sending it to the upstream proxy, even when you add it to every request in a Javascript request filter. The Javascript filter actually fires "between" the client and BMP, rather than between BMP and the upstream server/chained proxy. In embedded/Java mode, it's possible to create a filter that fires between BMP and the upstream server/chained proxy, but since you're using the REST API, that isn't available.

So, you're doing everything correctly, but BMP is thwarting you. Unfortunately chained proxy authentication is not currently supported, but let me think about this and see if I can come up with a good short-term solution.

**Comment by jekh** [comment]
This should now be resolved in master, using the parameters in #451. Let us know if you still have issues with it.

**Comment by natesreich** [comment]
Confirmed working. Thank you!

**Comment by s-belichenko** [comment]
Hello. I am using a standalone browsermob proxy version. To add a new proxy, I use this:
`curl -X POST "http://localhost:8080/proxy?httpProxy=server:port&proxyUsername=nameproxyPassword=pass"`

After that, I get this warning:

> Chained proxy support through setOptions is deprecated. Use setUpstreamProxy() to enable chained proxy support.

What should I use now?
