### ISSUE TITLE
proxy return error 503 for some resources

### ISSUE THREAD

**Issue by jpereira06** [lightbody/browsermob-proxy#367]
When I run http://losbalagaresgolf.com/ through the proxy some resources (images, fonts,...) return 503 error. The error resources vary between each execution. 
These problems are not reproducible neither with firebug neither chrome dev tools.

Please find attached a sample har:
[losbalagaresgolf_har.txt](https://github.com/lightbody/browsermob-proxy/files/81290/losbalagaresgolf_har.txt)

This error is also reproducible with http://www.cadvisionsl.com/

**Comment by jpereira06** [comment]
response objects are like following:

HttpObjectAggregator$AggregatedFullHttpResponse(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 0, widx: 323, cap: 323, components=1))
HTTP/1.1 503 Service Temporarily Unavailable
Date: Thu, 07 Jan 2016 15:04:06 GMT
Server: Apache
X-SERVER: 132
Content-Length: 323
Connection: close
Content-Type: text/html; charset=iso-8859-1

**Comment by jekh** [comment]
HTTP 503 means that the server is telling the proxy that it is temporarily unavailable. For the two URLs you listed, the problem appears to be that the server is returning a 503 when there are "too many" simultaneous requests. I was able to reproduce the error without a proxy by setting the `network.http.max-persistent-connections-per-server` value in Firefox to 32 (via about:config).

Ultimately, the server configuration should be changed so that it doesn't limit the number of connections from a single client to an extremely small value. To work around the issue, you can limit the number of server connections from your browser to the proxy by setting the `network.http.max-persistent-connections-per-proxy` property to a suitably small number, such as 6, in Firefox's about:config (I'm sure there's an equivalent setting in Chrome, too).

**Comment by jpereira06** [comment]
Thanks!
