### ISSUE TITLE
browser mob c# , Post data= null

### ISSUE THREAD

**Issue by danielBenAdi** [lightbody/browsermob-proxy#380]
i need to export only the Post data from the Ajax calls
and i get all the other info except the post data 

C# code 
  var opt = new ChromeOptions();
   server = new Server("C:\\temp\\browsermob-proxy-2.1.0-beta-4\\bin\\browsermob-proxy.bat");                 
   client = server.CreateProxy();
   client.NewHar("Paypo");
   Proxy seleniumProxy = new Proxy { HttpProxy = client.SeleniumProxy };
   opt.Proxy = seleniumProxy;
   HarResult harData = client.GetHar();

harData.Entry.Request.PostData  is null

**Comment by jekh** [comment]
It looks like you haven't enabled content capture in the HAR. By default, the contents of requests and responses is not captured in the HAR file because it would consume an enormous amount of memory. However, you can enable it by enabling the REQUEST_CONTENT and RESPONSE_CONTENT capture types. I'm not sure how the c# wrapper works, but the legacy Java interface had a setCaptureContent() method that may be exposed through the wrapper.

**Comment by danielBenAdi** [comment]
i cant find  a setCaptureContent() commend  for c#  syntax

**Comment by jekh** [comment]
Unfortunately I can't help with the c# wrapper. You'll probably have to ping the maintainer of that wrapper to enquire.

Alternately, you could run BMP in standalone and use the REST API.

**Comment by axtens** [comment]
I have my own REST library, coded before I discovered RestSharp, that does the capture content thing

            FluentREST fr = new FluentREST("http://localhost:8080/proxy");
            fr.Url("http://localhost:8080/proxy/" + port + "/har");
            fr.Verb("PUT").Tail("captureContent=true&initialPageRef=slurp").Send();

**Comment by jekh** [comment]
Since this does seem to be answered, I'll go ahead and close the issue.
