### ISSUE TITLE
Does REST API request interception work properly?

### ISSUE THREAD

**Issue by bobtuna** [lightbody/browsermob-proxy#391]
I am trying to change some header ('host', 'user-agent', etc.) more than one times.
First, interception is changing the header, but when I am trying to change it later - noting is changing.
* Start simple http headers printer (Node.js version here [headerPrinter.js
](https://gist.github.com/bobtuna/540260fec3b47ab5ada0#file-headerprinter-js)) on 127.0.0.1:80. 
* `java -jar browsermob-dist-2.1.0-beta-4.jar -address 127.0.0.1 -port 9090`

* `curl -X POST http://localhost:9090/proxy`

* `{"port":8081}`

* `curl --proxy http://127.0.0.1:8081 -X GET http://127.0.0.1:80`

*  `{"host":"127.0.0.1","user-agent":"curl/7.47.1","accept":"*/*","via":"1.1 browsermobproxy"}` - The **'user-agent'** header was established in value **'curl...' by default**.

*  `curl -i -X POST -d "request.headers().remove('User-Agent');request.headers().add('User-Agent','First attempt');" http://localhost:9090/proxy/8081/filter/request --header "Content-Type:text/plain"`-  **trying** to establish **'user-agent'** in value **'First attempt'**

*  `HTTP/1.1 200 OK
Content-Type: text/plain
Content-Length: 0
Server: Jetty(7.x.y-SNAPSHOT)`

* `curl --proxy http://127.0.0.1:8081 -X GET http://127.0.0.1:80`

* `{"host":"127.0.0.1","accept":"*/*","content-length":"0",*"user-agent":"First attempt"*,"via":"1.1 browsermobproxy"}
` - fine, this **works properly**. As we can see the 'user-agent' header is changing.

* `curl -i -X POST -d "request.headers().remove('User-Agent');request.headers().add('User-Agent','Second attempt');" http://localhost:9090/proxy/8081/filter/r
equest --header "Content-Type:text/plain"` - **trying** to establish **'user-agent'** in value **'Second attempt'**

* `curl --proxy http://127.0.0.1:8081 -X GET http://127.0.0.1:80`

* `{"host":"127.0.0.1","accept":"*/*","content-length":"0",*"user-agent":"First attempt"*,"via":"1.1 browsermobproxy"}
` - heck, this **works wrongly**. As we can see the 'user-agent' header does not changing to value 'Second attempt'.

Can you tell me, how we can updating current header value?

**Comment by borick** [comment]
I have the same issue with REST API interception for modifying Response content. It works randomly. By inspecting the code it relies on "HTTP message aggregation" or some such thing, the code says in browsermob-core-littleproxy/src/main/java/net/lightbody/bmp/filters/Response/RequestFilterAdapter.java

"HTTP message aggregation will be enabled if <i>any</i> filter has a maximum request or response buffer size greater than 0." but this doesn't seem to always work for me. Sometimes requests just aren't processed. Other-times they are but contents is set to null and I get a null pointer error. I had this working by some fluke combination of HTTP requests but figured out over last day or so that the robustness of this functionality is like spinning plates. I haven't been able to determine exactly what is causing this, tried a whole bunch of different things and looked at debug log. It does seem to happen for more "complex" requests, whatever that means, harder to reproduce in an isolated example, but was still able to.

I'm looking into other available proxy solutions now or something that can be done at JavaScript layer, but not much is out there that I can find.

**Comment by borick** [comment]
I have issues with inconsistent response filtering which may be related, I have raised in https://github.com/lightbody/browsermob-proxy/issues/399

**Comment by bobtuna** [comment]
>... inconsistent response filtering ...

Unfortunately, I am always getting constantly behavior of interception request. It is changing content (headers in my case) only once.
Now I am using [headers override method](https://github.com/lightbody/browsermob-proxy#rest-api) for changes. But, I don't know, what I will do, when I need to modify responses or requests more than once.

**Comment by jekh** [comment]
@bobtuna - Sorry about getting back so late; I missed your original issue for some reason. You've unfortunately run into a few of the limitations of the current filters implementation, which are combining to thwart your efforts. I'll go over the issues one by one and try to recommend a solution.

1. There is no way to remove a Javascript filter you've already added via the REST API; POSTing Javascript filters to `/filter/request` "appends" the filters, rather than replacing them. This means if you POST two filters that each add or modify the same header, BOTH filters will apply. This unfortunate reality is further compounded by:
2. The last Javascript request filter you POST is the first filter called. This means that, once you add a Javascript request filter that is adding a header, you essentially are stuck with it, since any subsequent filters you add will be trigger _before_ your original filter.
3. All Javascript request filters are invoked before any BMP filters are invoked. Adding headers, blacklisting, har capture, etc. all happen after executing your Javascript request filter. This is why using the header manipulation functionality works, even after manipulating the header in a Javascript request filter.

In the short term, your best bet if you need to frequently change the user agent header is to use the header override method you mentioned. If you need to "replace" Javascript filters, currently the only way to do so is to delete the old proxy and start a new proxy (POST to /proxy), which is far from ideal.

During the REST API refactor that I have planned for 2.2, we're definitely going to be adding more robust filter controls, including the ability to delete existing filters, and to specify where in the chain to add new filters.

**Comment by bobtuna** [comment]
Thank you for deep explanation. I am waiting for forthcoming REST API changes and will be asking you about some issues, which I have discovered.
