### ISSUE TITLE
Add ability to force a version of TLS

### ISSUE THREAD

**Issue by ashishplal** [lightbody/browsermob-proxy#407]
We currently have an issue where Browsermob is using TLS 1.0 and a site only accepts TLS 1.2. I don't know if this feature already exists or not, but it would be very helpful.

Thanks!

**Comment by jekh** [comment]
TLS 1.2 should be enabled by default on Java 8 JVMs. Java 7 disables it on the client side by default, and unfortunately (to my knowledge) does not provide a system property to enable it.

My advice is to use Java 8 if at all possible, since it allows much better customization of TLS versions through system properties. Alternately, you could use the netty+native openssl module, which should also support TLS 1.2 out of the box: http://netty.io/wiki/forked-tomcat-native.html. (Assuming you're using the littleproxy module, which you should do!)

I don't have any plans to allow adding a "force protocol" option to BMP, though if it were done in a non-invasive way (i.e. system property), I'd accept a PR for that feature.

**Comment by ashishplal** [comment]
Awesome, thanks so much!

**Comment by riccardoroasio** [comment]
Hi,

I have installed java8 but now what I have to do to enable tlsv1.2 in browsermob?

Thanks,
Riccardo

**Comment by jekh** [comment]
Nothing at all. It's enabled by default.
