### ISSUE TITLE
BrowsermobProxy does not capture har logs for Microsoft Edge

### ISSUE THREAD

**Issue by jayantsarda** [lightbody/browsermob-proxy#457]
Hi 
BrowserMob version 2.0.0

below is my script. 
`// start the proxy
ProxyServer server = new ProxyServer(4444);
server.start();
//captures the moouse movements and navigations
server.setCaptureHeaders(true);
server.setCaptureContent(true);

Proxy proxy = server.seleniumProxy();
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(CapabilityType.PROXY, proxy);

WebDriver driver = new EdgeDriver(capabilities);
server.newHar("har123");

driver.get("http://yahoo.com");

// get the HAR data
Har har = server.getHar();
server.stop();
driver.quit();  `

My scripts work perfectly fine for chrome and firefox. When I try similar setup with MicrosoftEdge. The Scripts as normal but no Har entries are captured."server.getHar()" returns blank.

in the log it says  trying to read status from localhost<port> (not the exact error message)

My question: 
1. Does BrowserMob work with MS Edge?
2. Does Edge needs any specific settings. My URL is a https url.
3. Do we have a sample setup for MS edge with browsermob?

**Comment by jekh** [comment]
BMP works for Edge and for any other HTTP client that is configured to use BMP as the proxy. Since it's working for you for Chrome and Firefox, this sounds like a question for the folks that maintain the Selenium WebDriver for Edge.

On a side note, 2.0.0 is not supported any longer. I recommend upgrading to 2.1.0.

**Comment by gitgrimbo** [comment]
FYI, I've seen something similar.  My scenario:

- Using Selenium Grid (v2.53.1).
- Asking for Edge browser (Edge v13, [MicrosoftWebDriver v2.10586](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/)). Passing in BMP as the proxy in the Selenium capabilities.
- Edge not using the proxy settings in the capabilities object, therefore putting no HTTP traffic through BMP.

Edge version:
![browsermob-457](https://cloud.githubusercontent.com/assets/1020541/18032668/19e18d14-6d04-11e6-97e4-9f5629841714.png)

What I see:

- BMP creates the HARs correctly as and when I ask it to.  I.e. the HAR file is created, and the HAR has pages for every call to `newPage()` I make.
- As there is no proxy traffic coming through BMP (because Edge has not set the proxy correctly), the HARs have no request data.
- Chrome running on the same Selenium node as Edge sets the proxy correctly and sends requests via BMP.

Workaround:

- I have had to manually set the Edge proxy settings on that particular Selenium node. Traffic now gets routed via BMP.

**Comment by gitgrimbo** [comment]
Related?

- Issue raised against Microsoft WebDriver - [*Proxy configuration capability for Microsoft WebDriver.*](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5468949/)

**Comment by jayantsarda** [comment]
@gitgrimbo Can you elaborate what changes will be needed in the Edge Browser proxy settings ? 
thanks

**Comment by gitgrimbo** [comment]
- open the Edge browser
- set its proxy manually to host `H` and port `P`
- start BMP on host `H` and port `P`
- run tests
