### ISSUE TITLE
Support for RemoteWebDriver

### ISSUE THREAD

**Issue by breinjhel** [lightbody/browsermob-proxy#47]
Hi,

First of all thank you for this wonderful tool and great job. 

I just need to know if there is anyway to support RemoteWebDriver because right now. I can add the proxy capability to a RemoteWebDriver. But I cannot seem to get the har file or requests. Is this not yet implemented? Or is this impossible to do so?

Thanks,
Christopher

**Comment by thibaut-sticky** [comment]
Sorry to up with issue, but @breinjhel 's question seems me good. It would be really nice to control a remote BMP server.
```JAVA
ProxyServer server = new ProxyServer("myproxy@ddress, "9090);
```

**Comment by jekh** [comment]
@thibaut-sticky Do you mean you want to control an _embedded_ proxy server remotely, via an HTTP REST (or other) API? You could do that by hooking up your API layer to the ProxyServer instance (that's what the standalone mode does with sitebricks), but why would you want to do that instead of running the proxy in standalone mode?

Embedded mode is designed to run in application code (generally, but not necessarily, Selenium tests), whereas the standalone mode is designed to be run as a separate application, complete with REST API. You can control a remote proxy running in standalone mode by directly calling the RESTful web services it exposes.

**Comment by thibaut-sticky** [comment]
My idea was to put a standalone BMP proxy server and Selenium Grid on a remote machine. So on this remote machine the tests would work but when writting or debugging my test on my local machine it would fail because I can not say to the JAVA API where is the server.
But finally, I choose the embedded mode, and it fix my issue.

**Comment by jekh** [comment]
Okay. I don't fully understand your use case, but it looks like you've solved the issue. I'm going to close this issue. Feel free to reopen if you feel this is a new feature you'd like to see implemented.
