### ISSUE TITLE
How can make my mobile device listen to browserMobProxy server?

### ISSUE THREAD

**Issue by vm31** [lightbody/browsermob-proxy#472]

**Comment by jigarladhava** [comment]
You haven't specified your mobile device specification.
I asuume it's android.(Since this project in is JAVA)
Android uses the Dalvik VM, whereas you need the Java VM to run a jar-file
You can configure your phone for using Java VM to run browserMobProxy without modifications.
else ,use src of this git to build your own.

**Comment by jekh** [comment]
It is certainly possible to use embedded-mode BMP on an Android project without recompiling BMP.

To get a mobile device to use BMP, you have to configure its proxy server settings. That varies widely by mobile device, so I would start there.
