### ISSUE TITLE
Documentation: rest: header is not active by default, port: should be 8080+

### ISSUE THREAD

**Issue by djtm** [lightbody/browsermob-proxy#479]
http headers such as
```
Last-Modified:
X-Clacks-Overhead:
```
do not end up in the json generated with REST by default (though if specifically requested). According to https://github.com/lightbody/browsermob-proxy/blob/master/README.md#rest-api headers should be enabled by default.

Also, the docs mostly contain port 9090+, while the default settings appear to be port 8080+. This can be a bit confusing for a newcomer. `sed s/909/808/` might do the trick.

**Comment by jekh** [comment]
You're absolutely right; header capture was disabled by default, mostly because cookie headers were taking up a huge amount of space in the HAR, but the documentation wasn't updated.

I'll update the docs for the new REST API (currently in the works); in the meantime, would you like to submit a PR for the current docs?
