### ISSUE TITLE
Unable to find cached IP address for host

### ISSUE THREAD

**Issue by madoni** [lightbody/browsermob-proxy#484]
Hi,
I am running a simple test to open cnn.com home page, using the corporate proxy as a `ChainedProxy`. The test runs fine but I see this warning in the logs:
`WARN net.lightbody.bmp.filters.HarCaptureFilter - Unable to find cached IP address for host: www.cnn.com. IP address in HAR entry will be blank.`

It appears that `ResolvedHostnameCacheFilter.getPreviouslyResolvedAddressForHost` always returns `null` when invoked from `populateAddressFromCache` inside `HarCaptureFilter`.

Is there something I'm missing in the `ChainedProxy` configuration?

**Comment by jekh** [comment]
This makes sense, though I hadn't thought of it till now: Since the chained proxy is actually resolving the address of the remote server, BMP doesn't know what IP address the request is sent to.

You can ignore this WARN message; the IP address should be blank when using a chained proxy. I'll suppress that message for chained proxies.

**Comment by madoni** [comment]
Yes... it hasn't really caused any issues... just "looks" like something is amiss!
Suppressing the warning works for me.

On the other hand, although I don't have any immediate need for this, would it be possible for the chained proxy to communicate this information to BMP... for the sake of completeness in terms of har capture?

**Comment by jekh** [comment]
This issue should now be fixed in master. There's no mechanism for an upstream proxy to communicate the IP address of a remote host, so the IP address must be blank.

**Comment by madoni** [comment]
I appreciate the support... thank you very much!

**Comment by madoni** [comment]
Hi,
I built the code from master and tested. Looks like this issue is resolved.
However, I see a similar message from `net.lightbody.bmp.filters.HttpConnectHarCaptureFilter`.
Does that need to be suppressed too?

**Comment by jekh** [comment]
Yes, you're right, I missed that. I've never been happy with the code duplication between those classes. In any case, this should be fixed in master now!

If this looks good, I'll probably release another minor version, since there have been several dependency updates, including a few security-related ones.

**Comment by madoni** [comment]
Looks like it's sorted out!
Thanks!

I see another message that wasn't there earlier... Is this related? Should I create a new issue for this?

```
14:54:15.304 [LittleProxy-0-ProxyToServerWorker-5] INFO org.littleshoot.proxy.impl.ProxyToServerConnection - (HANDSHAKING) [id: 0x88ddded7, L:0.0.0.0/0.0.0.0:54076 ! R:<proxy>/<proxy-ip>:<port>]: Connection to upstream server via chained proxy failed
java.nio.channels.ClosedChannelException: null
	at io.netty.handler.ssl.SslHandler.channelInactive(...)(Unknown Source)
```

**Comment by jekh** [comment]
@madoni - That looks like a separate issue. Can you open a separate issue, and include more of the stack trace and the surrounding BMP logs? Thanks!
