### ISSUE TITLE
Using HostNameResolver for https requests

### ISSUE THREAD

**Issue by SupersonicShiran** [lightbody/browsermob-proxy#495]
Hey,

I'm trying to make this remap:
https://init.mycompany.com --> https://platform-sandbox.mycompany.com

I've configured the proxy and the host resolver this way:

        net.lightbody.bmp.BrowserMobProxyServer mProxyServer;
        AdvancedHostResolver advancedHostResolver;

        mProxyServer = new BrowserMobProxyServer();

        mProxyServer.setHarCaptureTypes(REQUEST_HEADERS,
                REQUEST_COOKIES,
                REQUEST_CONTENT,
                REQUEST_BINARY_CONTENT,
                RESPONSE_HEADERS,
                RESPONSE_COOKIES,
                RESPONSE_CONTENT,
                RESPONSE_BINARY_CONTENT);

        mProxyServer.setTrustAllServers(true);
        advancedHostResolver = mProxyServer.getHostNameResolver();
        advancedHostResolver.remapHost("init.mycompany.com", "platform-sandbox.mycompany.com");
        mProxyServer.setHostNameResolver(advancedHostResolver);
        mProxyServer.start(8888);

Yet when I'm making a request to init.mycompany.com I see that the request is not remapped to the host platform-sandbox.mycompany.com. 
Did I missed anything?

Thanks!

**Comment by jekh** [comment]
When you say that the request is not remapped, do you mean in the HAR? The HAR looks at the HTTP request from the HTTP client; it isn't aware of host name remappings. 

In your example, the client still thinks it's connecting to init.mycompany.com, and the Host header as well as the SNI field in the TLS connection will show init.mycompany.com. But when BMP resolves the address internally, it will actually look up the IP address for platform-sandbox.mycompany.com. It's basically the same as changing your /etc/hosts file. One interesting consequence of this is that, if the remapped host is on the same server as the original host, it will actually be routed to the original host's virtual server, rather than the remapped host. Do both of these hosts resolve to the same IP address?

Host name remapping is also not supported when using an upstream chained proxy, since BMP doesn't actually resolve the host.

[I added a test](https://github.com/lightbody/browsermob-proxy/blob/master/browsermob-core/src/test/groovy/net/lightbody/bmp/proxy/RemapHostsTest.groovy) that shows host remapping in action.

**Comment by SupersonicShiran** [comment]
Actually I wan't counting on the HAR file. I looked at the response I received and the one I got matches the response of init.mycompany.com request and not platform-sandbox.mycompany.com.
And also those domains are not resolve to the same IP address...

**Comment by jekh** [comment]
If your remapping code looks like the code in the test I referenced (the test is written in groovy, but it's essentially the same in Java), then it should work (the test passes). You might need to debug to see what's going on. I'm not able to reproduce the issue running locally, but if you find something out, paste the info here and we can revisit.

**Comment by vijaygoturi** [comment]
Hi Jekh,

I am facing the issue with the HTTPS domains being remapped. Its not loading the required certificate from the server and is throwing "The request could not be satisfied."
