### ISSUE TITLE
HAR file results slower when using proxy compared to using selenium only

### ISSUE THREAD

**Issue by binyata** [lightbody/browsermob-proxy#529]
I am still new to using browsermob with selenium, but I am trying to understand what I could be missing...

The problem that I am facing is that when I check my HAR file results, manually, it takes me an average of 2 seconds or less to load up google.com, but if I add the browsermob proxy to the selenium chrome options, to run chromedriver, it takes me around 8+ seconds to load up google chrome.

Is there something I need to check, or is this a legitimate bug?

**Code:**

server = Server("browsermob-proxy-2.1.2/bin/browsermob-proxy")
server.start()
proxy = server.create_proxy()
print proxy.port

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--proxy-server={0}".format(proxy.proxy))
chrome_options.add_argument("--disable-component-extensions-with-background-pages")
browser = webdriver.Chrome(chrome_options = chrome_options)

proxy.new_har("google")
browser.get("https://google.com")
test1 = proxy.wait_for_traffic_to_stop(60, 120)
print test1

if test1 == 200:

```
harinfo = proxy.har # returns a HAR JSON blob
f = open('googletext.har', 'w')
f.write(json.dumps(harinfo))
f.close() 
server.stop()
browser.quit()
with open('googletext.har', 'r') as f:
    har_page = HarPage('google', har_data=json.loads(f.read()))
    print har_page.get_load_time(request_type=None, content_type=None, status_code=None, async=True)
```

**Comment by gitgrimbo** [comment]
Could you provide a HAR for both scenarios so that they can be compared on a request-by-request basis?

I ask because there is often a difference between the [`page.startedDateTime`](http://www.softwareishard.com/blog/har-12-spec/#pages) and the [first `entry.startedDateTime`](http://www.softwareishard.com/blog/har-12-spec/#entries) for that page.  This difference is due to the time difference between asking BMP to create a new page for the HAR, and the first request coming through BMP after a call to `driver.get(url)`, for example.

**Comment by Supakadoo** [comment]
Hello gitgrimbo, I have taken over the project on binyata's behalf.
Here are a couple of har files; one using broswermob and selenium taking 10 seconds to load the page, the other manually copying the har file from chrome taking 3 seconds.
[BMharfile.zip](https://github.com/lightbody/browsermob-proxy/files/457221/BMharfile.zip)

**Comment by gitgrimbo** [comment]
I wonder if it has something to do with SSL?  Can you try the test with HTTP rather than HTTPS?

**Comment by leoforever** [comment]
I also meet this problem. When I use browserModProxy, it is 2 minutes slower than use selenium only.

**Comment by Supakadoo** [comment]
@gitgrimbo I'm not able to control HTTP vs HTTPS for the sites we're interested in.

**Comment by gitgrimbo** [comment]
@Supakadoo - would you be able to set up any kind of HTTP vs HTTPS test?  Create a basic webapp to see if the slowdown is HTTPS only, or both?

**Comment by skyline-gleb** [comment]
Hi guys.
I have this problem too. With browserModProxy+Selenium first page load very slow on HTTPS (https://2gis.ru). On HTTP is Ok (http://help.2gis.ru).
```python
# python3.5
# coding: utf-8
# requirements: browsermob-proxy==0.7.1, selenium==2.53.5
import time
from selenium import webdriver
from browsermobproxy import Server

BROWSERMOB_PROXY = "/opt/browsermob-proxy-2.1.2/bin/browsermob-proxy"
CHROMEDRIVER = "/opt/chromedriver-2.21"
URL = "https://2gis.ru"

server = Server(path=BROWSERMOB_PROXY)
server.start()
proxy = server.create_proxy()
proxy.new_har(URL)

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--proxy-server={0}".format(proxy.proxy))
driver = webdriver.Chrome(executable_path=CHROMEDRIVER, chrome_options=chrome_options)
```
P.S. With Firefox, too, have this problem

**Comment by wDevil** [comment]
@gitgrimbo any ideas?

**Comment by gitgrimbo** [comment]
@wDevil, no sorry. Just making suggestions at the moment.

If HTTP traffic is not (problematically) slow, then the focus should be on HTTPS.

If HTTPS is an issue, then
- is the problem with startup only (e.g. bootstrapping the HTTPS subsystem), or
- is the problem with establishing SSL per domain, or
- is the problem with encrypting/decrypting each request, or
- is it a combination (or none) of these.

**Comment by leoforever** [comment]
Any update about this, I found ssl takes  lots of time  when https request. It is very severe.

**Comment by zhiying8710** [comment]
I also meet this problem.

**Comment by Idan37S** [comment]
Hi,

Since it seems it happens only with HTTPS, I believe the issue is with generating the certificates for the domains in order to use the MITM.

A possible solution is if we will be able to save those certificates and import them the next time we launch Browser mob proxy on that specific domain.

Any one knows a way to export\import those certificate?

**Comment by gitgrimbo** [comment]
There are certificate examples listed on this readme page:

https://github.com/lightbody/browsermob-proxy/blob/master/mitm/README.md

**Comment by Idan37S** [comment]
Hi @gitgrimbo ,
The link you gave talks about CA Root certificates,
I'm talking about the domain specific certificates which are being generated every time we access a new domain, those are the certificates that are being signed with the CA Root certificate,
And the problem is that they will be re-generated every launch of the proxy.

The CA Root certificate can be generated once and imported the next launch,
The question is, can this be done (export & import next launch) for the domain specific certificates as well?

**Comment by jekh** [comment]
BMP has to impersonate each domain's certificate, which is a relatively processor-intensive process. BMP doesn't currently support saving/loading previously-generated certificates, but feel free to open a new issue requesting that feature.

One way to speed up certificate generation is to use EC certificates instead of RSA. EC certs are supported by all modern browsers and are significantly faster to generate. You can enable EC generation in the REST API:
```sh
curl -X POST http://localhost:8080/proxy?useEcc=true
```
or in Embedded Mode:
```java
BrowserMobProxyServer proxy = new BrowserMobProxyServer();
proxy.setUseEcc(true);
//etc.
```

**Comment by HlebHalkouski** [comment]
@jekh can you add information about enable EC generation to readme?
