### ISSUE TITLE
Proxy server appears to cause loading issues on testing site

### ISSUE THREAD

**Issue by jessicamarshall** [lightbody/browsermob-proxy#606]
I am doing selenium automation testing and am using a standalone BMP server on each of our remote grid machines.  We are using the proxy server to bypass browser authentication.   I am also running parallel tests on each machine.  My issue is that when the proxy server is running, it slows down the browser so much that it ends up timing out.  3 out of 5 tests will typically fail because the browser loads so long (3-5 minutes).  It seems to do fine when 1 test (1 browser instance) is running, but when we do 5 tests running at a time, the tests just tank.  I can run all 5 tests parallel without the BMP server, and they do not have the loading issue.  We have to use a proxy server for the authentication to our site - as there are 3 different authentication servers that will pop up during various places in the test (and you are not able to pass the credentials into the URL in one of those places).

My question is - should the BMP server be able to handle multiple browsers going at once?  

My other thought - is that we have a BMP server running on each machine.  Would it be better to have a dedicated machine that just runs the proxy server - and have all the machines point to that one?  This is related to the above questions - as to whether the BMP server can handle (or was designed to) handle that type of traffic.  

Related details: We are using azure machines that are some what lightweight - 2 cores with 7GB.  Each machine will either run chrome (latest) or firefox (version 45).  We are using the latest release of BMP server - and only Rest commands are to start it on port 9091, and to pass in the authentication credentials.

**Comment by jekh** [comment]
The proxy should _definitely_ be able to handle a large number of browsers at once. I use a single embedded mode instance of BMP to handle traffic from dozens of browsers on a Selenium grid. A couple ideas come to mind:

- Since you're using the REST API, create the proxy using the `useEcc=true` query param, e.g. `curl -X POST http://localhost:8080/proxy?useEcc=true`. If BMP is proxying a large number of HTTPS requests from various hosts, this will definitely reduce CPU usage (RSA keys are expensive to generate, EC keys are quick).
- Are you setting any JAVA_OPTS on the command line that would affect heap usage?
- Try enabling debug-level logging in the `bmp-logging.yaml` and see if that gives a clue about what it's spending so much time doing.

To answer your other question, either running one per node or a single instance should work just fine. BMP really shouldn't be using all that many resources.

**Comment by jessicamarshall** [comment]
Thanks so much for you quick & helpful response.  using the useEcc=true query parameter made a huge difference and has eliminated the loading issue.

**Comment by jekh** [comment]
Glad that fixed the problem, I'll close this issue.

**Comment by raghuhit** [comment]
@jekh why ecc was not the default encryption method, even though it is faster, are there any cons to using this?
