### ISSUE TITLE
HTTP Pipelining

### ISSUE THREAD

**Issue by tarunmangla** [lightbody/browsermob-proxy#721]
I wanted to know how does BrowserMob proxy handles HTTP pipelining? Would it send the pipelined requests one by one or would it send them as they arrive?

**Comment by mediga** [comment]
Browsermob proxy does not queue any request/response, it just proxies them and sends and receives the requests as they occur

**Comment by tarunmangla** [comment]
Thanks for the reply. 

Just to confirm: This is what the wiki page says about HTTP pipelining in HTTP 1.1 "Most HTTP proxies do not pipeline outgoing requests." Does browsermob-proxy not fall into this category? If no, then how does it handle HTTP pipelining? 

Also, here is a related issue https://github.com/lightbody/browsermob-proxy/issues/540
Would pipelining work fine if a har is not captured in browsermob-proxy?

Thanks once again.

**Comment by mediga** [comment]
i would suggest to experiment to verify if http pipeline will work if browser uses browsermob as proxy vs it does not use browsermob proxy.   I am assuming since browsermob is mostly a passthrough pipelining should not be impacted, but better to do a couple of expirements.

Experiment steps:

turn on pipelining on firefox
1) run firefox WITHOUT browsermob and export the .har manually from developer tools. save the .har to a file
2) run firefox WITH browsermob and  export the .har manually from developer tools. save the .har to a file
3) compare .har from #1 vs #2, also check if browser is issuing any errors on console for #2
